# Generated by Django 2.1.7 on 2019-03-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pyctivex', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'default_permissions': (), 'ordering': ['-document'], 'permissions': (
                ('add_user', 'Crear usuarios'), ('change_user', 'Actualizar un usuario'),
                ('list_user', 'Consultar usuarios'), ('retrieve_user', 'Consultar un usuario'),
                ('add_groups', 'Crear un grupo'), ('change_groups', 'Actualizar un grupo'),
                ('list_groups', 'Consultar grupos'), ('retrieve_groups', 'Consultar un grupo')),
                     'verbose_name': 'Usuario',
                     'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='user',
            name='login_type',
            field=models.CharField(choices=[('LDAP', 'Directorio activo'), ('APPLICATION', 'Aplicación')],
                                   default='LDAP',
                                   help_text='<span style="color: red; font-weight: bold;">*</span> Seleccione tipo',
                                   max_length=20, verbose_name='Tipo de login'),
        ),
    ]

